// ISO 4217 currency catalogue used across Turgite.
// Names sourced from the currency-api catalogue (public data).
export interface Currency {
  code: string;
  name: string;
  symbol: string;
  exponent: number; // number of minor-unit digits
}

export const CURRENCIES: Currency[] = [
  { code: "AED", name: "Emirati Dirham", symbol: "د.إ", exponent: 2 },
  { code: "AFN", name: "Afghan Afghani", symbol: "", exponent: 2 },
  { code: "ALL", name: "Albanian Lek", symbol: "", exponent: 2 },
  { code: "AMD", name: "Armenian Dram", symbol: "", exponent: 2 },
  { code: "ANG", name: "Dutch Guilder", symbol: "", exponent: 2 },
  { code: "AOA", name: "Angolan Kwanza", symbol: "", exponent: 2 },
  { code: "ARS", name: "Argentine Peso", symbol: "AR$", exponent: 2 },
  { code: "AUD", name: "Australian Dollar", symbol: "", exponent: 2 },
  { code: "AWG", name: "Aruban or Dutch Guilder", symbol: "", exponent: 2 },
  { code: "AZN", name: "Azerbaijan Manat", symbol: "₼", exponent: 2 },
  { code: "BAM", name: "Bosnian Convertible Mark", symbol: "", exponent: 2 },
  { code: "BBD", name: "Barbadian or Bajan Dollar", symbol: "", exponent: 2 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", exponent: 2 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", exponent: 2 },
  { code: "BHD", name: "Bahraini Dinar", symbol: "", exponent: 3 },
  { code: "BIF", name: "Burundian Franc", symbol: "", exponent: 0 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "", exponent: 2 },
  { code: "BND", name: "Bruneian Dollar", symbol: "", exponent: 2 },
  { code: "BOB", name: "Bolivian Bolíviano", symbol: "", exponent: 2 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", exponent: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "", exponent: 2 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "", exponent: 2 },
  { code: "BWP", name: "Botswana Pula", symbol: "", exponent: 2 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "", exponent: 2 },
  { code: "BZD", name: "Belizean Dollar", symbol: "", exponent: 2 },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", exponent: 2 },
  { code: "CDF", name: "Congolese Franc", symbol: "", exponent: 2 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", exponent: 2 },
  { code: "CLP", name: "Chilean Peso", symbol: "CLP$", exponent: 0 },
  { code: "CNY", name: "Chinese Yuan Renminbi", symbol: "¥", exponent: 2 },
  { code: "COP", name: "Colombian Peso", symbol: "CO$", exponent: 2 },
  { code: "CRC", name: "Costa Rican Colon", symbol: "", exponent: 2 },
  { code: "CUP", name: "Cuban Peso", symbol: "", exponent: 2 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "", exponent: 2 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", exponent: 2 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "", exponent: 0 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", exponent: 2 },
  { code: "DOP", name: "Dominican Peso", symbol: "", exponent: 2 },
  { code: "DZD", name: "Algerian Dinar", symbol: "", exponent: 2 },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£", exponent: 2 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "", exponent: 2 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "", exponent: 2 },
  { code: "EUR", name: "Euro", symbol: "€", exponent: 2 },
  { code: "FJD", name: "Fijian Dollar", symbol: "", exponent: 2 },
  { code: "FKP", name: "Falkland Island Pound", symbol: "", exponent: 2 },
  { code: "GBP", name: "British Pound", symbol: "£", exponent: 2 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", exponent: 2 },
  { code: "GGP", name: "Guernsey Pound", symbol: "", exponent: 2 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "", exponent: 2 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "", exponent: 2 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "", exponent: 2 },
  { code: "GNF", name: "Guinean Franc", symbol: "", exponent: 0 },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "", exponent: 2 },
  { code: "GYD", name: "Guyanese Dollar", symbol: "", exponent: 2 },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", exponent: 2 },
  { code: "HNL", name: "Honduran Lempira", symbol: "", exponent: 2 },
  { code: "HRK", name: "Croatian Kuna", symbol: "", exponent: 2 },
  { code: "HTG", name: "Haitian Gourde", symbol: "", exponent: 2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", exponent: 2 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", exponent: 2 },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪", exponent: 2 },
  { code: "IMP", name: "Isle of Man Pound", symbol: "", exponent: 2 },
  { code: "INR", name: "Indian Rupee", symbol: "₹", exponent: 2 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "", exponent: 3 },
  { code: "IRR", name: "Iranian Rial", symbol: "", exponent: 2 },
  { code: "ISK", name: "Icelandic Krona", symbol: "", exponent: 0 },
  { code: "JEP", name: "Jersey Pound", symbol: "", exponent: 2 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "", exponent: 2 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "", exponent: 3 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", exponent: 0 },
  { code: "KES", name: "Kenyan Shilling", symbol: "", exponent: 2 },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "", exponent: 2 },
  { code: "KHR", name: "Cambodian Riel", symbol: "", exponent: 2 },
  { code: "KMF", name: "Comorian Franc", symbol: "", exponent: 0 },
  { code: "KPW", name: "North Korean Won", symbol: "", exponent: 2 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", exponent: 0 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "", exponent: 3 },
  { code: "KYD", name: "Caymanian Dollar", symbol: "", exponent: 2 },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", exponent: 2 },
  { code: "LAK", name: "Lao Kip", symbol: "", exponent: 2 },
  { code: "LBP", name: "Lebanese Pound", symbol: "", exponent: 2 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", exponent: 2 },
  { code: "LRD", name: "Liberian Dollar", symbol: "", exponent: 2 },
  { code: "LSL", name: "Basotho Loti", symbol: "", exponent: 2 },
  { code: "LYD", name: "Libyan Dinar", symbol: "", exponent: 3 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "", exponent: 2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "", exponent: 2 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "", exponent: 2 },
  { code: "MKD", name: "Macedonian Denar", symbol: "", exponent: 2 },
  { code: "MMK", name: "Burmese Kyat", symbol: "", exponent: 2 },
  { code: "MNT", name: "Mongolian Tughrik", symbol: "", exponent: 2 },
  { code: "MOP", name: "Macau Pataca", symbol: "", exponent: 2 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "", exponent: 2 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "", exponent: 2 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "", exponent: 2 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "", exponent: 2 },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$", exponent: 2 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", exponent: 2 },
  { code: "MZN", name: "Mozambican Metical", symbol: "", exponent: 2 },
  { code: "NAD", name: "Namibian Dollar", symbol: "", exponent: 2 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", exponent: 2 },
  { code: "NIO", name: "Nicaraguan Cordoba", symbol: "", exponent: 2 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", exponent: 2 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", exponent: 2 },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", exponent: 2 },
  { code: "OMR", name: "Omani Rial", symbol: "", exponent: 3 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "", exponent: 2 },
  { code: "PEN", name: "Peruvian Sol", symbol: "", exponent: 2 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "", exponent: 2 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", exponent: 2 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", exponent: 2 },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", exponent: 2 },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "", exponent: 0 },
  { code: "QAR", name: "Qatari Riyal", symbol: "QR", exponent: 2 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", exponent: 2 },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", exponent: 2 },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", exponent: 2 },
  { code: "RWF", name: "Rwandan Franc", symbol: "", exponent: 0 },
  { code: "SAR", name: "Saudi Arabian Riyal", symbol: "﷼", exponent: 2 },
  { code: "SBD", name: "Solomon Islander Dollar", symbol: "", exponent: 2 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "", exponent: 2 },
  { code: "SDG", name: "Sudanese Pound", symbol: "", exponent: 2 },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", exponent: 2 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", exponent: 2 },
  { code: "SHP", name: "Saint Helenian Pound", symbol: "", exponent: 2 },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "", exponent: 2 },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "", exponent: 2 },
  { code: "SOS", name: "Somali Shilling", symbol: "", exponent: 2 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "", exponent: 2 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "", exponent: 2 },
  { code: "STN", name: "Sao Tomean Dobra", symbol: "", exponent: 2 },
  { code: "SYP", name: "Syrian Pound", symbol: "", exponent: 2 },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "", exponent: 2 },
  { code: "THB", name: "Thai Baht", symbol: "฿", exponent: 2 },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "", exponent: 2 },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "", exponent: 2 },
  { code: "TND", name: "Tunisian Dinar", symbol: "DT", exponent: 3 },
  { code: "TOP", name: "Tongan Pa'anga", symbol: "", exponent: 2 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", exponent: 2 },
  { code: "TTD", name: "Trinidadian Dollar", symbol: "", exponent: 2 },
  { code: "TVD", name: "Tuvaluan Dollar", symbol: "", exponent: 2 },
  { code: "TWD", name: "Taiwan New Dollar", symbol: "NT$", exponent: 2 },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "", exponent: 2 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", exponent: 2 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "", exponent: 0 },
  { code: "USD", name: "US Dollar", symbol: "$", exponent: 2 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "", exponent: 2 },
  { code: "UZS", name: "Uzbekistani Som", symbol: "", exponent: 2 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "", exponent: 2 },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", exponent: 0 },
  { code: "VUV", name: "Ni-Vanuatu Vatu", symbol: "", exponent: 0 },
  { code: "WST", name: "Samoan Tala", symbol: "", exponent: 2 },
  { code: "XAF", name: "Central African CFA Franc BEAC", symbol: "", exponent: 0 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "", exponent: 2 },
  { code: "XOF", name: "CFA Franc", symbol: "", exponent: 0 },
  { code: "XPF", name: "CFP Franc", symbol: "", exponent: 0 },
  { code: "YER", name: "Yemeni Rial", symbol: "", exponent: 2 },
  { code: "ZAR", name: "South African Rand", symbol: "R", exponent: 2 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "", exponent: 2 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "", exponent: 2 },
];

export function currencyByCode(code: string): Currency | undefined {
  const c = code.toUpperCase();
  return CURRENCIES.find((x) => x.code === c);
}

export function currencySymbol(code: string): string {
  return currencyByCode(code)?.symbol || code.toUpperCase();
}

export function currencyExponent(code: string): number {
  return currencyByCode(code)?.exponent ?? 2;
}
